### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by brainscript**
Thank you for this great app! I really love it! :heart_eyes:
So I thought, why not contribute to it with a German translation. :smiley_cat:

_@mikepenz And please add the missing translation strings like "Backup Loved", "Import Loved" and the description on the "Open Source" page. Having and app 100% translated really improves the UX._

### CODE REVIEW

**Comment by mikepenz** [comment]
@brainscript thank you. 

The descriptions on the open source page come from the `AboutLibraries` which provides the details for used libraries. I think it will be a bit hard to translate all of them.

**Comment by brainscript** [comment]
@mikepenz Ok, but stuff like the "Nothing new!" or "5 new pictures ..." toasts and the buttons I mentioned in the first post should be no problem to translate, right?

**Comment by mikepenz** [comment]
That's the full `strings.xml` 

https://file.io/bTNKO4

**Comment by brainscript** [comment]
@mikepenz I know, I took the English one and translated it to German.
But why are these strings missing?

**Comment by mikepenz** [comment]
@brainscript v2.x of wallsplash was not open sourced because many people stole the code without permissions and just sold it. It includes many optimizations inlcluding a few features, for which the strings are missing. 

v1.x was already very stable. So I kept it open source

**Comment by brainscript** [comment]
@mikepenz Are you talking about [Wall Splash for unsplash.com](https://play.google.com/store/apps/details?id=com.unsplash.wallsplash)?
I already wondered why they use almost exactly the same description ...

```
* over 15000 images
* browse the images
* "love" the best images and use them later
```

Did you report their app on Google Play?
That's obviously not legit, because your repo description and the license state ...

`You have to give credits (Attribution)`
:arrow_right_hook: They did not credit you.

`You are allowed to used it in any free application (NonCommercial)`
:arrow_right_hook: They have ads in their app.

The "developer" also stole the source of the [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager&hl=de) app.

**Comment by mikepenz** [comment]
@brainscript yeah it looks really similar. But I am not 100% sure it is really based on mine. Could be. 

It is really hard to report those if you can't 100% proof it. 

That's why I do no longer have it open source and keep the detail improvements closed source

**Comment by brainscript** [comment]
@mikepenz I'd still like to help you with the translations. Could you upload the full English strings.xml somewhere? The https://file.io/bTNKO4 is not working.

**Comment by mikepenz** [comment]
@brainscript I will upload again. :D the above file had a timeout of 24 hours

**Pull request closed without merging**
